### PR TITLE
Fix `useIsomorphicLayoutEffect` usage in React Native environments

### LINKED ISSUE #2150: Connected children components might have mapStateToProps not called
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 0.73.5
- Redux: 5.0.1
- React Redux: 9.1.0

### What is the current behavior?

In my react native app, I have connected parent components which might contain connected children components (react navigation top material tabs). The child components might dispatch action to change its state, but sometimes the state of the child components is not refreshed, mapStateToProps is not called at all. It's not an issue about mutable state because if I change to another tab and return back, the state is correctly refreshed and subsequent state change after this is correctly refreshed. I moved back from 9.1.0 to 8.1.3, and the problem is solved.

### What is the expected behavior?

mapStateToProps should be called whenever store state change.

### Which browser and OS are affected by this issue?

react native ios

### Did this work in previous versions of React Redux?

- [X] Yes

### PR DESCRIPTION
**Pull request by aryaemami59**
## __Overview__

It looks like React Native was not using `useLayoutEffect` which was causing nested component updates to not get properly batched when using the `connect` API. 

## __This PR__:

  - [X] Fixes `useIsomorphicLayoutEffect` usage in React Native environments. 
  - [X] Fixes #2150.
  
Possible related issues: #1313, #1444, #1510, #1436.
  
I did test the actual build with `yalc`, React Native, Expo and Expo web seem to be working properly. We can probably get rid of [`src/utils/useIsomorphicLayoutEffect.native.ts`](https://github.com/reduxjs/react-redux/blob/master/src/utils/useIsomorphicLayoutEffect.native.ts) file, so let me know if you want me to do that I can include it in this PR or a separate one.

### CODE REVIEW

File: src/utils/useIsomorphicLayoutEffect.ts [hunk 1]
```diff
@@ -16,6 +16,18 @@ export const canUseDOM = !!(
...
+ */
+export const isReactNative =
+  typeof navigator !== 'undefined' && navigator.product === 'ReactNative'
+
 export const useIsomorphicLayoutEffect = canUseDOM
   ? React.useLayoutEffect
-  : React.useEffect
+  : isReactNative
+    ? React.useLayoutEffect
+    : React.useEffect
```
Comment (sdg9) [inline src/utils/useIsomorphicLayoutEffect.ts:33]: Not sure if there is a convention in this repo but since `canUseDOM` or `isReactNative` want `useLayoutEffect` you could avoid the second ternary in favor of just doing a `||`

```suggestion
export const useIsomorphicLayoutEffect = canUseDOM || isReactNative 
  ? React.useLayoutEffect
  : React.useEffect
```

**Comment by markerikson** [comment]
*sigh* of _course_ it was the `useLayoutEffect` issue, _again_.

File: src/utils/useIsomorphicLayoutEffect.ts (hunk 1 above)
Comment (aryaemami59) [reply src/utils/useIsomorphicLayoutEffect.ts:33]: Yup, sounds good.

**Comment by aryaemami59** [comment]
@markerikson hopefully this'll be the end of it :), just wondering do you think I should also switch the `target` for the main entry point from `es2020` to `esnext`?

**Comment by aryaemami59** [comment]
@sdg9 Thanks for the repro, it made debugging very easy!

**Comment by sdg9** [comment]
I'm rephrasing https://github.com/reduxjs/react-redux/issues/2150#issuecomment-2041518174 with the fix of this PR in my own words as I want to make sure I understand what is going on.

1. Before react-redux v9 you used a [.native.js suffix](https://github.com/reduxjs/react-redux/commit/b832f835d76ec9d1fcfbdee6c80d497df5dbca06#diff-2cc3fb4125a84f0b15c9eac8264ec8574a6ac595e566ba2c8bf104fbdd3b5ca9R1-R5) to differentiate behavior for ReactNative.  In ReactNative `useIsomorphicLayoutEffect` was explicitly set to `useLayoutEffect`, while the other file had DOM vs server logic.
2. With the react-redux upgrade to v9, the npm artifact was pre-bundled to a single js file.  This change eliminated the use of the `native.js` suffix, which inadvertently caused React Native to be handled the same way as server environments (using `useEffect`) as react-native is not DOM based.  
3. With this PR ReactNative once again uses `useLayoutEffect`.  

Is this an accurate understanding?

Just curious, diving more into # 2, it seems like the impetus of having a conditional driving `useIsomorphicLayoutEffect` is to differentiate server environments vs all others (based on comments in the modified file on how `useLayoutEffect` triggers warnings on servers).  
Would it make more sense to structure the conditional logic to something like the following?
```js
export const useIsomorphicLayoutEffect = isServer ? useEffect : useLayoutEffect
```
  I ask because had it been written this way this issue would never have ocurred when the `native.js` file was dropped, React-Native would have defaulted to the client behavior rather than the server behavior.

I can understand if this is easier said than done, for example I imagine it's easier/more consistent to check if we're running in a DOM vs react-native environment than to check if it's Node.js/server but I'm not certain, hence the question.

**Comment by markerikson** [comment]
Yep, that's a good summary.  (And ironically, that warning is going away in React 19.)

Yeah, tweaking the conditional that way would make sense, I think.

**Comment by aryaemami59** [comment]
@markerikson Do you want me to include further tweaks in this PR or separate?

**Comment by sdg9** [comment]
What about a two pronged approach? Move forward with this PR as-is since we know it resolves the issue. This will unblock RN consumer like myself immediately and really keeps behavior identical to how things were in v8.x
  Then if desired discuss long term whether the conditional makes sense to keep as-is or tweak it based on my question which is more of a forward looking potential preventative measure.

**Comment by markerikson** [comment]
Okay, out in https://github.com/reduxjs/react-redux/releases/tag/v9.1.1 !
