### PR TITLE
Convert Provider into function component with hooks

### LINKED ISSUE #1370: Provider uses previous store for one additional render when store changes
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

If a the `store` passed to a `Provider` changes the `store` in `ReactReduxContext` does not update until the next render.  This is causing me an issue the `children` are changing, causing the to crash when trying to `mapStateToProps` in that additional render.

[Sandbox.](https://codesandbox.io/s/thirsty-cherry-f49el)

Note: this is a contrived example to to show how this occurs, but I have an real world case using React Router V5 that has the same issue.

Also Note: my use case is not to have a distinct store per page, but actually using `redux-subspace` to create a virtual sub-store per page.  Again, I didn't bother with this detail for the example as it occurs with real stores too.

**What is the expected behavior?**

I would expect that if `Provider` permits me to change the store, that a `connect`ed component below it would not crash when rendering.  I believe the root of the issue is the fact that [the store is not updated in the `Providers`'s state until `componentDidUpdate`](https://github.com/reduxjs/react-redux/blob/master/src/components/Provider.js#L38-L45), but the render the would result in this update already has the new `this.props.children` value.

I do concede that this is a pretty niche use case, and may not be the highest priority to fix (assuming you agree that it is an issue at all).

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

```json
"react": "16.8.6",
"react-dom": "16.8.6",
"redux": "4.0.4"
"react-redux": "7.1.0",
```

### PR DESCRIPTION
**Pull request by mpeyper**
Fixes issue where the `store` and `children` values were updated in different render passes which could result in `mapState` errors if the new children were not compatible with the old store.

The change to a function component meant `Provider` could take advantage of `useEffect` to "watch" the `store` prop and unsubscribe to the old store and subscribe to the new store.

Fixes #1370

### CODE REVIEW

File: src/components/Provider.js [hunk 1]
```diff
@@ -1,62 +1,35 @@
...
-    const { store } = props
-
-    this.notifySubscribers = this.notifySubscribers.bind(this)
+function Provider({ store, context, children }) {
+  const contextValue = useMemo(() => {
     const subscription = new Subscription(store)
-    subscription.onStateChange = this.notifySubscribers
-
-    this.state = {
+    subscription.onStateChange = subscription.notifyNestedSubs
```
Comment (mpeyper) [inline src/components/Provider.js]: This is what I determined `subscription.onStateChange = this.notifySubscribers` to actually boiled down to.  I'm wondering if `subscription` couldn't just handle this internally?

File: test/components/Provider.spec.js [hunk 2]
```diff
@@ -312,5 +312,43 @@ describe('React', () => {
       ReactDOM.unmountComponentAtNode(div)
       expect(spy).toHaveBeenCalledTimes(1)
     })
+
+    it('should handle store and children change in a the same render', () => {
```
Comment (mpeyper) [inline test/components/Provider.spec.js]: I did verify that this did actually fail on the old code before making my change.

File: src/components/Provider.js [hunk 3]
```diff
@@ -1,62 +1,35 @@
...
 
-    if (this.previousState !== this.props.store.getState()) {
-      this.state.subscription.notifyNestedSubs()
+    if (previousState !== store.getState()) {
+      subscription.notifyNestedSubs()
     }
-  }
-
-  componentWillUnmount() {
-    if (this.unsubscribe) this.unsubscribe()
```
Comment (mpeyper) [inline src/components/Provider.js]: I could not see where `this.unsubscribe` was actually being set.  I think this could have been safely removed, but the new implementation does not allow for this in any way, so if that is an issue I'll have to go back to the drawing board.

**Comment by markerikson** [comment]
Hey, thanks for putting this together!  I'll have to come back and look at it a bit later, but noted.

File: src/components/Provider.js (hunk 3 above)
Comment (markerikson) [reply src/components/Provider.js]: Yeah, I think this line is a leftover artifact from pre-7.0 that I missed removing.

File: src/components/Provider.js (hunk 1 above)
Comment (timdorr) [reply src/components/Provider.js]: We use the same Subscription class for the `connect` components, where this is part of our top-down update mechanic. So, it needs to stay configurable. This is just a quirk of re-use.

**Comment by mpeyper** [comment]
hey @markerikson/@timdorr, have either of you had a chance to take a look at this yet?

**Comment by timdorr** [comment]
Looks good to me. @markerikson?

File: src/components/Provider.js [hunk 4]
```diff
@@ -1,62 +1,35 @@
...
-  }
-
-  componentDidUpdate(prevProps) {
-    if (this.props.store !== prevProps.store) {
-      this.state.subscription.tryUnsubscribe()
-      const subscription = new Subscription(this.props.store)
-      subscription.onStateChange = this.notifySubscribers
-      this.setState({ store: this.props.store, subscription })
+    return () => {
+      subscription.tryUnsubscribe()
```
Comment (markerikson) [inline src/components/Provider.js]: Given what we just saw in #1380 , let's clear out the change callback here too:

```suggestion
     subscription.tryUnsubscribe()
     subscription.onStateChange = null
```

**Comment by markerikson** [comment]
Okay, board is green.  LGTM!

**Comment by mpeyper** [comment]
Hey, just curious what the release timeframe is on this.  Is there a specific milestone this will wait for or will a `7.1.1` version get pushed out soon?

**Comment by markerikson** [comment]
Good question.  @timdorr , you got time to drop a new release with this and the memory clear tweak?

I'm at React Rally this week.  Busy with the conf the next two days.  Hoping to do some maintainer-ish stuff on the weekend.  If it's not out by then, I'll try to publish it.

**Comment by mpeyper** [comment]
No major rush from me, just curious.

**Comment by timdorr** [comment]
This is out as [7.1.1](https://github.com/reduxjs/react-redux/releases/tag/v7.1.1) now!

File: src/components/Provider.js (hunk 1 above)
Comment (MichaelSnowden) [reply src/components/Provider.js:9]: I know this is a very old PR, but I'm wondering if you ever tested this in `StrictMode`? I'm noticing bugs where updates stop happening for us using `react-redux` 7.2.5, and I believe it's because we set `onStateChange` here in the `useMemo` callback, but then we clear it [here](https://github.com/reduxjs/react-redux/pull/1377/files#diff-ac6af22b2cd4dd0f3ae1c7a43037607d1d32f0d65fce060da62c92dcdb9eaab5R27) in the `useEffect` teardown. With strict mode, the `useMemo` callback here will run twice, but the result of the second run isn't actually used. So, the result is that children are rendered with the original subscription which is resubscribed but has no `onStateChange` callback, so it does nothing. I think the fix is to move this line to the `useEffect` call. I can patch that for us locally, but I'm wondering if you ever encountered this after making this change.

Comment (MichaelSnowden) [reply src/components/Provider.js:9]: Ahh, I see https://github.com/reduxjs/react-redux/commit/6acb58de1a2e93666bfec5e515d1aaea846e88d9 now

Comment (markerikson) [reply src/components/Provider.js:9]: @MichaelSnowden yeah, we actually fixed that bug in https://github.com/reduxjs/react-redux/releases/tag/v7.2.8 :)  latest 7.x release is 7.2.9.  (But also, we would recommend upgrading to v8.x if possible if you're still on React 17 or earlier, or v9 if you're on React 18.)

Comment (markerikson) [reply src/components/Provider.js:9]: Strict Mode would be the only real reason I can think of that this would be an issue off the top of my head.
